### ISSUE TITLE
GTK2 some images missing...

### ISSUE THREAD

**Issue by kernhe** [L4ki/Mega-Plasma-Themes#2]
/.themes/Mega-GTK/gtk-2.0/main.rc:2435: Unable to locate image file in pixmap_path: "assets/toolbar-button-hover.png"
/.themes/Mega-GTK/gtk-2.0/main.rc:2438: Background image options specified without filename
/.themes/Mega-GTK/gtk-2.0/main.rc:2445: Unable to locate image file in pixmap_path: "assets/toolbar-button-active.png"
/.themes/Mega-GTK/gtk-2.0/main.rc:2448: Background image options specified without filename
/.themes/Mega-GTK/gtk-2.0/main.rc:2453: Unable to locate image file in pixmap_path: "assets/toolbar-button-active.png"
/.themes/Mega-GTK/gtk-2.0/main.rc:2456: Background image options specified without filename

**Comment by L4ki** [comment]
Hi kernhe,

Thank you for the information. For the following updating I will add image missing files.

Greetings,
